global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:3001']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      # Thay a.b.c.d bằng IP của máy chủ Jenkins
      - targets: ['localhost:8080']
    
  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']