global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['app:3001']
  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']